---
title: "Computing access"
---

You can choose 2 ways of working with Python.

# Online

To access computing resources for this course we will make use of the [Google Colab](https://colab.research.google.com/) computing services linked to the course drive storage.
The link to the Google Drive can be found at [Useful links](https://bovi-analytics.github.io/BeastsAndBytes/course-links.html)

Make sure you get familiar with Google Colab by reading and trying to run your first pieces of code in the '[Welcome To Colaboratory](https://colab.research.google.com/notebooks/basic_features_overview.ipynb)' notebook.
We recommend using Colab as it will be easier to work simultaneously with your group mates on the project. 

The Dodona exercises can also be done in colab. Make sure to make a folder with your name to store your notebooks within the Google Drive environment.
Google offers a free premium version of colab for Cornell students, you can register for this using your Cornell email adress. 

# Offline

You can also chose to work in Python on your desktop. This can be done using PyCharm in combination with an Anaconda environment, as configured through Dodona. If you encounter any confusion related to these differences or the environment setup, feel free to reach out to the TA for assistance. Other python interperters like VS code also work. 
