---
title: "Course support"
---

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## Lectures and labs

If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a peer teaching opportunity for everyone.

## Office hours

The entire teaching team is here to support your success in this course, and you are encouraged to ask questions about course content, assignments, or logistics. Many questions are most effectively addressed in person. Office hours are therefore offered on a flexible, appointment-based basis to accommodate teaching schedules. Please reach out in advance to arrange a meeting time. Even if you do not have specific questions, you are welcome to schedule a brief meeting to introduce yourself and say hello. Meike also has a walk in office hour at Wednesday 3-5 pm.

## Weekly assignments

Each week holds a 'Programming assignment deadline' the day before the next lab (monday 12 pm). It is important that you stick to these deadlines as your correct submissions for this deadline will be used for the final grading. You are welcome to work on that during the week in your own time, but dedicated lab hours are blocked within each week.

Teaching assistants will be available during these hours if you require help or feedback.

## Discussion forum

Have a question that might be valuable for all course participant? Prefer to write out your question in detail rather than asking in person? The online discussion forum is the best venue for these! We will use [github issue](https://github.com/Bovi-analytics/BeastAndBytes/issues) as the online discussion forum. There is a chance another student has already asked a similar question, so please check the other posts before adding a new question. If you know the answer to a question that is posted, I encourage you to respond!

## Email

Please refrain from emailing any course content questions (those should go here [github issue](https://github.com/Bovi-analytics/BeastAndBytes/issues)), and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.).

For such matters, you may email Dr. Miel Hostens at [miel.hostens\@cornell.edu](mailto:miel.hostens@cornell.edu).

## **Course materials costs**

There are no costs associated with this course. All readings will come from freely available, open resources (open-source textbooks, journal articles, etc.).

## **Assistance with Teams**

Teams will be used for online office hours as well as as a backup option should we need to hold the course online instead of in person.
