---
title: "Data Science Applications in Agriculture"
tbl-colwidths: [5,5,15,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the course.\
Note that this schedule will be updated as the course progresses, with all changes documented here.

::: column-screen-inset-right
| Week | Date | Topic | Teachers | Prepare | Lecture |
|:----------:|:----------:|------------|------------|:----------:|:----------:|
| 1 | 1/20 (Tue) | Introduction to Python programming | Meike van Leerdam | [📖](https://forms.office.com/r/bDEBaU5fN1) | [🖥️](slides/lec-1.html) |
| 1 | 1/21 (Wed) | Introduction to decision support | Meike van Leerdam | [📖](https://www.ibm.com/think/topics/data-driven-decision-making) | [🖥️](slides/discussion_1.html) |
| 2 | 1/26 (Mon) | Cancelled -\> Lec moved to lab | Dr. Hostens | [📖](weeks/week-2.html) | [🖥️](slides/lec-2.html) |
| 2 | 1/27 (Tue) | Introduction to the project | Dr. Hostens | 📖 | [🖥️](slides/lec-1.html) |
| 2 | 1/28 (Wed) | Project discussion | Dr. Hostens | \- | -️ |
| 3 | 2/2 (Mon) | Work on Dodona at home |  |  |  |
| 3 | 2/3 (Tue) | RUFAS lecture and programming assignment | H. Hu and K. Reed | [📖](https://www.jdscommun.org/article/S2666-9102(25)00195-4/fulltext) | [🖥️](https://youtu.be/0jBReNID8R8) |
| 3 | 2/4 (Wed) | Project discussion | Meike van Leerdam | 📖 | 🖥️ |
| 4 | 2/9 (Mon) | [Guest lecture](https://teams.microsoft.com/meet/2793529249127?p=SOTWGPJVrtZBDhyGsu) | [Dr. de Vries](https://animal.ifas.ufl.edu/people/albert-de-vries/) | [📖](weeks/week-4.html) | [🖥️](https://youtu.be/6TGTDjSkqZU) |
| 4 | 2/10 (Tue) | Programming assignment | TAs | \- | \- |
| 4 | 2/11 (Wed) | Project discussion with farmer | D. Westfall & M. van Leerdam | \- | 🖥️ |
| 5 | 2/16 (Mon) | February break | \- | \- | \- |
| 5 | 2/17 (Tue) | February break | \- | \- | \- |
| 5 | 2/18 (Wed) | [Guest lecture](https://teams.microsoft.com/meet/27062365396024?p=rNcIgJIJFvcr98DkNZ) | [Dr. Cabrera](https://andysci.wisc.edu/directory/victor-cabrera/) | [📖](weeks/week-5.html) | [🖥️](https://youtu.be/QDNlWDeyCCY) |
| 6 | 2/23 (Mon) | Project discussion | Dr. Miel Hostens | 📖 | 🖥️ |
| 6 | 2/24 (Tue) | Programming assignment | TAs | 📖 | 🖥️ |
| 6 | 2/25 (Wed) | FAIR data principles for Animal/Agricultural Science | Dr. Hostens | 📖 | [🖥️](slides/lec-6.html) |
| 7 | 3/2 (Mon) | MyCow\$ | Dr. Giordano | 📖 | 🖥️ |
| 7 | 3/3 (Tue) | Programming assignment | TAs | \- | -️ |
| 7 | 3/4 (Wed) | Effective visualisation using Tableau | Dr. Hostens | 📖 | [🖥️](https://prezi.com/view/8Pgr5LLExlIaYtktADox/) |
| 8 | 3/9 (Mon) | DISC Assessment & Team DynamicS | Dr. Hostens | [📖](weeks/week-8.html) | [🖥️](slides/lec-8.html) |
| 8 | 3/10 (Tue) | Farm visit | Dr. Hostens and TAs | \- | \- |
| 8 | 3/11 (Wed) | Discuss results DISC | Dr. Hostens | 📖 | 🖥️ |
| 9 | 3/16 (Mon) | Project discussion | Dr. Miel Hostens | 📖 | 🖥️ |
| 9 | 3/17 (Tue) | Discuss MSCW frontend and start backend | Meike | 📖 | 🖥️ |
| 9 | 3/18 (Wed) | Project discussion | Dr. Hostens and Meike | 📖 | 🖥️ |
| 10 | 3/23 (Mon) | Project discussion | Dr. Hostens and Meike | 📖 | 🖥️ |
| 10 | 3/24 (Tue) | Work on project | self | 📖 | 🖥️ |
| 10 | 3/25 (Wed) | Curse of dimensionality | Dr. Hostens | 📖 | 🖥️ |
| 11 | 3/30 (Mon) | Spring break | \- |  |  |
| 11 | 3/31 (Tue) | Spring break | \- |  |  |
| 11 | 4/1 (Wed) | Spring break | \- |  |  |
| 12 | 4/6 (Mon) | Software and Azure | Bart de Zoete | 📖 | [🖥️](https://canvas.cornell.edu/courses/83180/files?preview=15179001) |
| 12 | 4/7 (Tue) | Work on project and programming assignment | Meike | 📖 | 🖥️ |
| 12 | 4/8 (Wed) | Project discussion | Dr. Hostens or Meike | 📖 | 🖥️ |
| 13 | 4/13 (Mon) | Project | Dr. Hostens or TAs | \- | -️ |
| 13 | 4/14 (Tue) | Project | Dr. Hostens or TAs | \- | -️ |
| 13 | 4/15 (Wed) | Project | Dr. Hostens or TAs | \- | -️ |
| 14 | 4/20 (Mon) | Project | Dr. Hostens or TAs | \- | -️ |
| 14 | 4/21 (Tue) | Project | Dr. Hostens or TAs | \- | -️ |
| 14 | 4/22 (Wed) | Project | Dr. Hostens or TAs | \- | -️ |
| 15 | 4/27 (Mon) | Project | Dr. Hostens or TAs | \- | -️ |
| 15 | 4/28 (Tue) | Project | Dr. Hostens or TAs | \- | -️ |
| 15 | 4/29 (Wed) | Project | Dr. Hostens or TAs | \- | -️ |
| 16 | 5/4 (Mon) | Project | Dr. Hostens or TAs | \- | \- |
| 16 | 5/5 (Tue) | Final project presentation | Dr. Hostens and TAs | \- | -️ |
| 17 | 5/14 (Thu) | Programming exam | Meike van Leerdam | MRS334 | -️ |
:::

```{r echo = FALSE}
knitr::knit_exit()
```
